
#-------------------------------------logging------------------------------

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    path: ./logs

#-------------------------------------port------------------------------

server:
  port: 3636

#-------------------------------------thymeleaf------------------------------

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  #-----------------------------------数据库配置-------------------------------------------------
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        minimum-idle: 3
        auto-commit: true
        idle-timeout: 10000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&allowMultiQueries=true&useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root

  main:
    allow-bean-definition-overriding: true
  #------------------------------------------------shiro-----------------------------------------------
shiro:
  enabled: true
  web:
    enabled: true
  loginUrl: /
  unauthorizedUrl: /index
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true

#--------------------------mybatis xml配置文件-------------------------------------------------
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.shiro.study.pojo
